### ISSUE TITLE
Mehrfache Änderung des Landes wirkt keine Änderung im Appell hervor

### ISSUE THREAD

**Issue by chloe-the-catgirl** [chloe-the-catgirl/corona-noergel-app#10]
d20f39a9d32908fef8b11fd182c63d4c535878bc sollte das Problem beheben, hat aber stattdessen #3 eingeführt. Der Bug existiert noch.

## Reproduzierbarkeit

1. beliebiges Bundesland auswählen
2. Appell mit "${Bundesland}" auswählen, Bundesland wird korrekt ersetzt
3. Bundesland wechseln
4. Appell enthält weiterhin das alte Bundesland

**Comment by benbender** [comment]
Das Problem ist, dass das reactive assignment `$: appelle = config.appell` die Abhängigkeit nicht so tief tracked, dass die Reaction ausgelöst wird, wenn sich der `empfänger` ändert.

Grundlegend ist das Problem hier beschrieben: https://svelte.dev/tutorial/updating-arrays-and-objects

Die Lösung ist wsl (untested), das `.map` in eine eigene Methode (bspw `setAnrede`) zu packen und den Empfänger dieser Methode als Parameter zu übergeben. Dann weiß Svelte, dass die Methode aufgerufen werden muss, wenn der Empfänger neu gesetzt wird und es sollte gehen.

Zudem ist mir eben aufgefallen, dass [das `value` hier](https://github.com/chloe-the-catgirl/corona-noergel-app/blob/ac3fd3d7ba5422b9b03512cb819358c385becd58/src/routes/index.svelte#L169) auf ein `[object]` gesetzt wird, weil sich da scheinbar die Datenstruktur geändert hat.

**Comment by chloe-the-catgirl** [comment]
Der Wert hat aber schon die richtige Struktur für den store. Ich bin mir nicht einmal sicher, ob es daran liegt, ich hab eher die Vermutung, dass das importierte JSON überschrieben wird und dann nicht mehr das replacement funktioniert, da der zu ersetzende Text nicht mehr existiert.

**Comment by benbender** [comment]
Das Problem ist nicht die Struktur, sondern wann die Zuweisung (`$: appelle = cna.appell`) neu evaluiert wird. Setz Dir mal 'nen `console.log(to, a);` in den `.map()`-closure und teste.

Ich wette ungesehen, dass der bei einer Änderung der Empfänger nicht aufgerufen wird. Der Svelte-Compiler tracked die Dependencies recht sicher nicht in die closures von `.filter()/.map()`... Das dürfte nur ausgelöst werden, wenn sich `cna.appell` ändert.

**Comment by chloe-the-catgirl** [comment]
Ah, okay, das werd ich morgen mal testen. Danke für die Hinweise und ausführlichen Erklärungen bis hierhin! ☺️

**Comment by benbender** [comment]
Gerne + kein Ding. Hab unter ähnlichen Problemen nur auch schon genug gelitten und hab eh auf durchgelaufene Container-builds gewartet. Ich drück Euch die Daumen!
