### ISSUE TITLE
Überprüfen der Barrierefreiheit

### ISSUE THREAD

**Issue by chloe-the-catgirl** [chloe-the-catgirl/corona-noergel-app#17]
Einige grundlegende Dinge sind bereits beachtet:

- Kontrast der Farben
- Abschalten der Animationen, sofern `prefers-reduced-motion` gesetzt ist
- keine zu kleinen Texte
- Label für jedes Input-Element

Was zusätzlich überprüft werden sollte:
- Vorlesen mit Screenreader
- Wechsel der Seite (etwa zum Impressum)
- rein tastatur-basierte Navigation

**Comment by xenein** [comment]
Firefox moniert: 
- introtext hat zu wenig Kontrast
- link im introtext hat zu wenig Kontrast

**Comment by chloe-the-catgirl** [comment]
Vielleicht mit 1cbab497cf3e99f8084a8271301faaff18acbb49 schon behoben, hatte das glücklicherweise relativ zeitnah festgestellt.

**Comment by benbender** [comment]
Ein paar Ideen/Anmerkungen:

- generell bei "Schritt 1: ..." usw die Gesamtzahl der Schritte mit angeben. Also "Schritt 1 von 4: ..." zB.
- die "Schritt X: ..." als <h2 /> und Überschrift auszeichnen, da eine <section /> eigentlich immer eine Überschrift haben sollte und es das Springen für Menschen mit Screenreadern vereinfacht. Alternativ könnte man die <section />'s auch durch <fieldset /> und <legend />'s ersetzen.
- Es kann sein, dass ggf. einige Screenreader das einblenden der nachfolgenden Form-Teile nicht mitschneiden und als Hinweis darauf ein "aria-live=polite" brauchen. Aus Accessibility-Sicht ist das unerwartete ein-/ausblenden von $Dingen leider immer eher doof...
- Alternativ wäre es evtl. gut, wenn zumindest die Headlines eingeblendet würden und "aria-expanded=false" hätten und dazu ein submit-button, der einen Fehler ausgibt, warum das Formular noch nicht abgesendet werden kann. Hilft wsl. auch generell bei der Orientierung auf der Seite. Aktuell ist Mensch ggf. etwas Lost was da noch kommt, weil es keine Hinweise/Orientierung gibt.
- Version & Links unten würde ich in einen <footer /> packen.

Hoffe das hilft!
