### ISSUE TITLE
Mehrfachauswahl der Elemente ermöglichen

### ISSUE THREAD

**Issue by chloe-the-catgirl** [chloe-the-catgirl/corona-noergel-app#20]
Es kam der Wunsch auf, nicht nur einen der Bausteine zu verwenden, sondern mehrere.

**Comment by chloe-the-catgirl** [comment]
Nicht sonderlich vom Nutzen überzeugt, wenn du (@xenein) nichts dagegen hast, würd ich das issue schließen und mit dem `wontfix`-Label versehen.

**Comment by xenein** [comment]
ich seh halt nicht, wie das smooth irgendwie ins Interface geht. Insofern ja, gerne schließen.
