### ISSUE TITLE
copy option for message and address

### ISSUE THREAD

**Issue by xenein** [chloe-the-catgirl/corona-noergel-app#22]
Wir könnten ein "kopieren" (wie in copy-paste) Feature für Mailadresse, Betreff und Nachricht einführen.

**Comment by chloe-the-catgirl** [comment]
Might be useful, probably. https://github.com/github/clipboard-copy-element

**Comment by benbender** [comment]
or even more sveltier: https://github.com/ghostdevv/svelte-copy 🥳

**Comment by chloe-the-catgirl** [comment]
Das ist ja noch bequemer, da fehlt dann nur noch bisschen CSS für den Button und fertig is. :3

**Comment by benbender** [comment]
Yepp. I ❤️  svelte-actions! 😸

**Comment by chloe-the-catgirl** [comment]
Das ist gut, Lust auf ein Merge Request? 😬

**Comment by benbender** [comment]
Leider keine zeitlichen Ressourcen :/ Aber nen Pointer auf die Lösung des Problems in #10 kommt gleich noch (immerhin!) ;)
