### ISSUE TITLE
Favicon wird unter Safari (macOS) nicht angezeigt

### ISSUE THREAD

**Issue by xenein** [chloe-the-catgirl/corona-noergel-app#23]
falls wir eines haben, brauchen wir ein favicon, das in Safari lädt.

**Comment by chloe-the-catgirl** [comment]
Okay, dann ist Safari der Browser, der keine svg-Favicons lädt, gut zu wissen. Chrome zeigt mir nämlich brav das 🦠 emoji an ^^

**Comment by xenein** [comment]
ah da hab ich gestern nicht mehr drauf geschaut. 

Safari:
![image](https://user-images.githubusercontent.com/76600392/151128393-f5a2b878-5fff-4168-8e35-a86add71463a.png)

Firefox:
![image](https://user-images.githubusercontent.com/76600392/151128559-203aa89f-a68a-428b-9a03-f0184d093859.png)

**Comment by xenein** [comment]
![image](https://user-images.githubusercontent.com/76600392/151164312-e68dd8ae-d59b-4dae-b4f8-8b0333b1bb06.png)
 🤔

**Comment by chloe-the-catgirl** [comment]
[caniuse](https://caniuse.com/link-icon-png) sagt, dass Safari Favicons in PNG unterstützt, keine Ahnung, warum der dennoch nicht will. Unter iOS läuft's nämlich. :D

**Comment by chloe-the-catgirl** [comment]
Xenia sagt, Problem tritt nicht mehr auf. Yay :3
