### ISSUE TITLE
OpenGraph-Bilder für GitHub

### ISSUE THREAD

**Issue by chloe-the-catgirl** [chloe-the-catgirl/corona-noergel-app#25]
Da @xenein so eine talentierte Grafikerin ist, darf sie auch gerne noch das GitHub-OpenGraph-Bild hinzufügen. Nicht sicher, ob du Zugriff auf die Repo-Einstellungen hast, aber da gibt's ein Template. Das aktuelle Bild passt leider nicht so ganz rein. ^^

**Comment by xenein** [comment]
ich hab keine Settings hier.

**Comment by chloe-the-catgirl** [comment]
> Images should be at least 640×320px (1280×640px for best display).

Und hier die entsprechende Vorlage. Danke :3
![Das GitHub-Template für OpenGraph-Bilder.](https://user-images.githubusercontent.com/98263758/151519287-5d095c29-b5fd-483b-9ae9-316a4f054216.png)

**Comment by xenein** [comment]
![image](https://user-images.githubusercontent.com/76600392/151527012-c7f5e701-cfb6-4dc1-985b-f7a39a3996c8.png)

ich bleib dabei, graphic design is my passion

**Comment by chloe-the-catgirl** [comment]
Magst du die Schrift in weiß setzen, Kontraste und so? 😬

**Comment by xenein** [comment]
![image](https://user-images.githubusercontent.com/76600392/151536472-6de92d88-f187-4f5e-9dbb-8c0c05e4a839.png)
sö?

**Comment by chloe-the-catgirl** [comment]
top :3
