### ISSUE TITLE
Unable to set Appell 

### ISSUE THREAD

**Issue by jeyemwey** [chloe-the-catgirl/corona-noergel-app#3]
Hi, thanks for your application which will certainly be useful.

Sadly, I’m unable to choose a value to the Appell Dropdown. When using the randomizer function, no value seems to be picked either. I hope that this can be fixed somehow?

Thanks again, also for publishing your code here.

**Comment by chloe-the-catgirl** [comment]
Hi, which device/browser are you using? Is JavaScript enabled?

**Comment by jeyemwey** [comment]
I have been trying with both Chrome/Android and Safari/iPadOS.

**Comment by chloe-the-catgirl** [comment]
I can reproduce it. Damn, going to fix it asap.
