### ISSUE TITLE
Schab kein Bock mehr.

### ISSUE THREAD

**Issue by chloe-the-catgirl** [chloe-the-catgirl/corona-noergel-app#48]
Allgemeiner Sammel-Ort für Beschwerde-Themen, ich fang an. 

https://twitter.com/____jeannette/status/1491505791228125196?s=21

**Comment by chloe-the-catgirl** [comment]
Also wirklich nicht. https://twitter.com/prienkarin/status/1492205554021904392?s=21

**Comment by chloe-the-catgirl** [comment]
https://twitter.com/telesabbie/status/1494347883725918209?s=21

**Comment by xenein** [comment]
https://twitter.com/ALMevTeam/status/1496092800181493764

**Comment by xenein** [comment]
https://twitter.com/miob1781/status/1498785731954847745

jo, I guess, irgendwer könnte mal Inhalte überarbeiten. @chloe-the-catgirl, na, morgen mal zusammen ein paar Formulierungen aus dem linken Nasenloch ziehen?

**Comment by chloe-the-catgirl** [comment]
Vielleicht, wenn ich Lust hab. 🙈

**Comment by xenein** [comment]
https://twitter.com/Ap_Saegge/status/1499148770918993920

**Comment by chloe-the-catgirl** [comment]
https://twitter.com/wdraktuell/status/1501171123907665920?s=21

**Comment by chloe-the-catgirl** [comment]
https://twitter.com/wdraktuell/status/1502268611498545154?s=21

**Comment by xenein** [comment]
https://twitter.com/nuernberg_de/status/1501955001995907073?s=21

klingt nach sehr entspannter Lage.

**Comment by chloe-the-catgirl** [comment]
https://twitter.com/derniederbayer/status/1502334464982147078?s=21

**Comment by chloe-the-catgirl** [comment]
> klingt nach sehr entspannter Lage.

ach du scheiße.

**Comment by chloe-the-catgirl** [comment]
Verlinkung darauf könnte nice sein: https://twitter.com/ashducation/status/1502693421236035584?s=21

**Comment by chloe-the-catgirl** [comment]
https://twitter.com/wdraktuell/status/1502999776694083584?s=21

**Comment by chloe-the-catgirl** [comment]
Wird vorerst aufgrund von Inaktivität geschlossen, Datensatz kann später wieder mit neuem Issue erweitert werden.
