### ISSUE TITLE
Integration weiterer Beschwerden

### ISSUE THREAD

**Issue by chloe-the-catgirl** [chloe-the-catgirl/corona-noergel-app#5]
Vorschlag: https://twitter.com/fraugodot/status/1485325066061729797?s=21

**Comment by chloe-the-catgirl** [comment]
Idee:

1. Hinzufügen eines `themen` (oder `topics`)-Knoten, der nen Namen und ne eindeutige ID enthält.
2. Die bestehende Datenstruktur als kompletten Unterknoten mit der ID versehen.

Beispiel:

```json
{
    "themen": {
        "pcr-test": "Aufhebung der PCR-Test-Pflicht",
        "impfung-u5": "Kinderimpfung (Off-Label)"
    },
    "data": {
        "pcr-test": {
            "appelle": [],
            "beschwerde": [],
        }
    }
}
```

Gruß und übergreifendes kann im Root verbleiben, der Rest wird so aber sauber getrennt.

**Comment by xenein** [comment]
ist schon Zeit über Tools, die das JSON-Schema kennen und spezifisch da drin Dinge bearbeiten können, nachzudenken?

**Comment by chloe-the-catgirl** [comment]
Nicht sicher, was du meinst:

1. JSON-Schema für die `data.json` basteln.
2. Anpassung der Daten über separates Tool.

**Comment by xenein** [comment]
naja, beides :D 

also solange sich das Schema nicht ändert aber bekannt ist, kann hinzufügen und bearbeiten safer sein.

**Comment by chloe-the-catgirl** [comment]
Kandidatin: https://twitter.com/rbb24/status/1487865745803468800?s=21
Kandidat: https://twitter.com/meine_kehrseite/status/1487822706586402824?s=21
