### ISSUE TITLE
Faxgeräte sind heilig

### ISSUE THREAD

**Issue by xenein** [chloe-the-catgirl/corona-noergel-app#7]
Wie wäre das, das Templateing auch in eine (Norm)Briefvorlage[1] zu tun, um mit einem zweiten Button neben dem MailTo-Button einen für Fax- oder Postversand zu erleichtern?
Also gäbe dann 1 weiteren Button, der ein eigenes Template mit den selben Infos ausfüllt, was dann eben den Brief/Fax gibt, so mit Adresse und Stuff. 
Nicht sicher, wie State of the Art javascript so ist, aber ich glaub nicht dran, dass das direkt nach PDF gehen kann (was ja nicht schlimm ist, weil der Browser einfach als PDF drucken kann). 

needs: 
- templating for letter
- address and fax data for all recipients

[1] https://github.com/mac-and-i/Normbrief-mit-Markdown (hat fertig gerendertes HTML im Repo, ließe sich ergänzen)

**Comment by chloe-the-catgirl** [comment]
Sollte machbar sein, kann die Druckfunktion des Browsers ja per JavaScript ansprechen und wenn das Template dann entsprechend gut genug aussieht, ist der Brief ja quasi erledigt.

**Comment by xenein** [comment]
Maybe, just maybe (ich weiß, was das Ding actually taugt):
http://raw.githack.com/MrRio/jsPDF/master/docs/module-html.html - das sieht zumindest so aus, als könnten wir mit dem HTML-Brief-Template von oben und diesem was bauen.

Müsste nur jemand Faxnummern und Postanschrifen auftreiben. (hab gehört, nonxens macht das gegebenenfalls.)
